spring.application.name=Kafica - Blokadica

server.port = 8181

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG


app.scheduling.deadline-check=0 * * * * *
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.messaging=TRACE
logging.level.org.springframework.messaging=DEBUG